# Generated by Django 2.1 on 2019-06-13 22:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='clipboard',
            name='file_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_app.FileContent'),
        ),
        migrations.AddField(
            model_name='clipboard',
            name='text_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='basic_app.TextContent'),
        ),
    ]
