# Generated by Django 2.1 on 2019-06-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='filecontent',
            name='filename',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
