# Generated by Django 2.1 on 2019-06-13 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190613_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
