# Generated by Django 2.1 on 2019-06-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_shareables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareables',
            old_name='cliboard_item',
            new_name='clipboard_item',
        ),
    ]
