# Generated by Django 2.1 on 2019-06-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20190625_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipboard',
            name='file_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.FileContent'),
        ),
        migrations.AlterField(
            model_name='clipboard',
            name='text_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.TextContent'),
        ),
    ]
