# Generated by Django 2.1 on 2019-06-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20190625_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareables',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
